services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
          - /var/lib/postresql/data
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=mongo
        ports:
            - 27017:27017
        volumes:
            - /var/lib/mongodb/data
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
    auction-svc:
        image: carties-auction/auction-svc:latest
        build: 
          context: .
          dockerfile: AuctionService/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:80
          - ASPNETCORE_URLS=http://+:7777
          - RabbitMq__Host=rabbitmq
          - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
          - IdentityServiceUrl=http://identity-svc
          - Kestrel__Endpoints__Grpc__Protocols=Http2
          - Kestrel__Endpoints__Grpc__Url=http://+:7777
          - Kestrel__Endpoints__WebApi__Protocols=Http1
          - Kestrel__Endpoints__WebApi__Url=Http://+:80
        ports:
          - 7001:80
          - 7777:7777
        depends_on:
          - postgres
          - rabbitmq
    search-svc:
        image: carties-auction/search-svc:latest
        build: 
          context: .
          dockerfile: SearchService/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:80
          - RabbitMq__Host=rabbitmq
          - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
          - AuctionServiceUrl=http://auction-svc
        ports:
          - 7002:80
        depends_on:
        - mongodb
        - rabbitmq
    identity-svc:
        image: carties-auction/identity-svc:latest
        build: 
          context: .
          dockerfile: IdentityService/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Docker
          - ASPNETCORE_URLS=http://+:80
          - ClientApp=http://app.carsties.com
          - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
          - VIRTUAL_HOST=id.carsties.com
        depends_on:
        - postgres
    gateway-svc:
        image: carties-auction/gateway-svc:latest
        build: 
          context: .
          dockerfile: GatewayService/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Docker
          - ASPNETCORE_URLS=http://+:80
          - ClientApp=https://app.carsties.com
          - VIRTUAL_HOST=api.carsties.com