services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
          - /var/lib/postresql/data
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=mongo
        ports:
            - 27017:27017
        volumes:
            - /var/lib/mongodb/data
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
    auction-svc:
        image: carties-auction/auction-svc:latest
        build: 
          context: .
          dockerfile: AuctionService/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:80
          - RabbitMq__Host=rabbitmq
          - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=auctions
          - IdentityServiceUrl=http://identity-svc
        ports:
          - 5234:80
        depends_on:
          - postgres
          - rabbitmq
    search-svc:
        image: carties-auction/search-svc:latest
        build: 
          context: .
          dockerfile: SearchService/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:80
          - RabbitMq__Host=rabbitmq
          - ConnectionStrings__MongoDbConnection=mongodb://root:mongo@mongodb
          - AuctionServiceUrl=http://auction-svc
        ports:
          - 5231:80
        depends_on:
          - mongodb
          - rabbitmq
    identity-svc:
        image: carties-auction/identity-svc:latest
        build: 
          context: .
          dockerfile: IdentityService/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Docker
          - ASPNETCORE_URLS=http://+:80
          - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=IdentityCarties
        depends_on:
        - postgres
        ports:
        - 5000:80
    gateway-svc:
        image: carties-auction/gateway-svc:latest
        build: 
          context: .
          dockerfile: GatewayService/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Docker
          - ASPNETCORE_URLS=http://+:80
        ports:
          - 6001:80